/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *HomePage;
    QProgressBar *BolusBar;
    QPushButton *OptionsButton;
    QPushButton *BolusButton;
    QProgressBar *BatteryBar;
    QDateTimeEdit *dateTimeEdit;
    QTextEdit *textEdit;
    QTextEdit *inuslinUnits;
    QPushButton *currentStatus;
    QWidget *currentStatusPage;
    QLabel *label_55;
    QPushButton *backToHome_5;
    QPushButton *buttonR;
    QPushButton *buttonR_2;
    QPushButton *buttonR_3;
    QPushButton *buttonR_4;
    QWidget *OffPage;
    QTextBrowser *textBrowser;
    QFrame *PINFrame;
    QLabel *label_3;
    QTextEdit *PIN;
    QLabel *ErrorPIN;
    QWidget *OptionsPage;
    QPushButton *SettingsButton;
    QPushButton *backToHome_2;
    QPushButton *myPumpBTN;
    QPushButton *startStopBTN;
    QPushButton *loadInsulinCartBTN;
    QPushButton *settingsDownButton;
    QLabel *label_50;
    QWidget *OptionsPage2;
    QPushButton *settingsUpButton;
    QPushButton *backToHome_4;
    QPushButton *historyBTN;
    QLabel *label_51;
    QWidget *historyPage;
    QPushButton *backToSettingsBTN;
    QPushButton *pumpHistoryBTN;
    QPushButton *cgmHistoryBTN;
    QLabel *label_49;
    QWidget *cgmHistoryPage;
    QPushButton *historyBTN_7;
    QLabel *label_54;
    QPushButton *historyBTN_8;
    QPushButton *backToHistoryBTN_2;
    QWidget *pumpHistoryPage;
    QPushButton *backToHistoryBTN;
    QLabel *label_53;
    QPushButton *historyBTN_5;
    QPushButton *historyBTN_6;
    QWidget *loadPage;
    QPushButton *backToOptionsBTN_2;
    QLabel *label_34;
    QPushButton *changeCartBTN;
    QWidget *stopDeliverPage;
    QLabel *label_35;
    QDialogButtonBox *cartStopConfirmBTN;
    QLabel *label_36;
    QWidget *disconnectPage;
    QLabel *label_37;
    QLabel *label_38;
    QDialogButtonBox *cartStopConfirmBTN_2;
    QWidget *insulinCartSizePage;
    QLabel *label_39;
    QSpinBox *insulinCartAmmountSpinBox;
    QPushButton *continueCartBTN;
    QLabel *label_40;
    QWidget *fillTubingPage;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QPushButton *fillTubingBTN_2;
    QWidget *setupForCannula;
    QLabel *label_44;
    QLabel *label_45;
    QPushButton *goToCannulaFillingBTN;
    QWidget *fillCannulaPage;
    QLabel *label_46;
    QLabel *label_47;
    QPushButton *fillCannulaBTN;
    QWidget *resumeInsulinPage;
    QDialogButtonBox *loadResumeBTN;
    QLabel *label_48;
    QWidget *SettingsPage_1;
    QGraphicsView *DTView;
    QGraphicsView *PINView;
    QLabel *DTLabel;
    QLabel *PINLabel;
    QLabel *label;
    QTextBrowser *CurrentPIN;
    QPushButton *DeletePINButton;
    QTextEdit *NewPIN;
    QPushButton *SetPINButton;
    QLabel *label_2;
    QLabel *ErrorNewPIN;
    QPushButton *DownButton;
    QDateTimeEdit *dateTimeEditor;
    QPushButton *backToHome_3;
    QWidget *SettingsPage_2;
    QGraphicsView *BluetoothView;
    QPushButton *UpButton;
    QLabel *label_5;
    QCheckBox *BluetoothCheckBox;
    QLabel *BTMess;
    QWidget *leaveBolusWarningPage;
    QLabel *label_12;
    QLabel *label_52;
    QDialogButtonBox *leaveBolusConfirm;
    QWidget *BolusPage;
    QPushButton *backToHome;
    QTextEdit *finalBolusUnits;
    QLabel *label_4;
    QPushButton *confirmBolusBTN;
    QLabel *label_6;
    QLabel *label_7;
    QPushButton *viewCalcBTN;
    QPushButton *enterCarbsBTN;
    QPushButton *addBgBTN;
    QLabel *label_8;
    QLabel *label_15;
    QWidget *deliverCalculationPage;
    QPushButton *backToBolus;
    QLabel *label_56;
    QTextEdit *correctionView;
    QLabel *label_57;
    QLabel *label_58;
    QTextEdit *foodView;
    QLabel *label_59;
    QTextEdit *iobView;
    QLabel *label_60;
    QTextEdit *totalUnitsToDeliverView;
    QLabel *label_61;
    QTextEdit *carbRatioView;
    QTextEdit *correctionFactorView;
    QLabel *label_141;
    QTextEdit *tagetBgView;
    QLabel *label_142;
    QLabel *label_143;
    QLabel *label_144;
    QLabel *label_145;
    QLabel *label_146;
    QLabel *label_147;
    QLabel *label_148;
    QWidget *enterCarbsPage;
    QTextEdit *textEdit_7;
    QPushButton *BTN0;
    QPushButton *addCarbsBTN;
    QLabel *label_9;
    QDoubleSpinBox *carbGramsSpinBox;
    QWidget *enterBgPage;
    QDoubleSpinBox *bgSpinBox;
    QTextEdit *textEdit_8;
    QLabel *label_14;
    QPushButton *addBgBTN_2;
    QPushButton *backToBolusBTN;
    QWidget *confirmBolusPage;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QTextEdit *conCarb;
    QTextEdit *conBG;
    QTextEdit *conUnits;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QDialogButtonBox *buttonBox;
    QWidget *deliverBolusPage;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QTextEdit *correctionAmount;
    QTextEdit *foodAmount;
    QLabel *label_26;
    QLabel *label_27;
    QDialogButtonBox *confirmBolBTN;
    QCheckBox *ExtensionCheckBox;
    QPushButton *editExtensionBTN;
    QWidget *extendedPage;
    QTextEdit *textEdit_9;
    QPushButton *setDeliveryTimeBTN;
    QPushButton *backToDeliverBTN;
    QLabel *label_28;
    QPushButton *deliverNowBTN;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QPushButton *extendedDurationBTN;
    QPushButton *viewExtendedUnitsBTN;
    QTextEdit *deliverLaterLabel2;
    QLabel *deliverLaterLabel;
    QWidget *deliverNowPercentagePage;
    QPushButton *backToExtendedPageBTN;
    QPushButton *setDeliverBTN;
    QTextEdit *textEdit_11;
    QSpinBox *deliverNowSpinbox;
    QWidget *timeDurationPage;
    QPushButton *setTimeDurBTN;
    QSpinBox *setHourSpinbox;
    QTextEdit *textEdit_12;
    QPushButton *backToExtendedPageBTN_2;
    QSpinBox *setMinSpinbox;
    QLabel *label_32;
    QLabel *label_33;
    QWidget *deliverConfirmPage;
    QTextEdit *deliverNowLabel;
    QDialogButtonBox *durationButtonBox;
    QLabel *label_67;
    QTextEdit *deliverLaterLabel_3;
    QTextEdit *durationLabel;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QWidget *finalBolusConfirmPage;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label_74;
    QTextEdit *bolusNowAndCorrectionLabel;
    QTextEdit *bolusLaterLabel;
    QTextEdit *finalTimeDurationLabel;
    QDialogButtonBox *finalConfirmBolusButtonBox;
    QWidget *intiatedExtendedPage;
    QLabel *label_75;
    QLabel *finalBolusUnitsLabel;
    QWidget *initialdedPage;
    QLabel *label_149;
    QLabel *finalBolusUnitsLabel_3;
    QWidget *lowChargeWarningPage;
    QLabel *label_10;
    QLabel *label_11;
    QWidget *myPumpPage;
    QPushButton *personalProfilesBTN;
    QPushButton *backToOptionsBTN;
    QPushButton *pumpInfoBTN;
    QWidget *personalProfilesPage;
    QPushButton *createProfilePageBTN;
    QPushButton *backToMyPumpBTN;
    QTableWidget *profileTable;
    QWidget *profileNameCreatePage;
    QLineEdit *profileNameLineEdit;
    QLabel *label_13;
    QPushButton *createProfileBTN;
    QLabel *nameErrorLabel;
    QPushButton *backToPersonalProfilesPageBTN;
    QPushButton *OnButton;
    QPushButton *OffButton;
    QPushButton *ChargeButton;
    QPushButton *UnplugButton;
    QPushButton *TandemLogo;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(803, 545);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 571, 521));
        HomePage = new QWidget();
        HomePage->setObjectName(QString::fromUtf8("HomePage"));
        BolusBar = new QProgressBar(HomePage);
        BolusBar->setObjectName(QString::fromUtf8("BolusBar"));
        BolusBar->setGeometry(QRect(450, 20, 111, 31));
        BolusBar->setValue(100);
        OptionsButton = new QPushButton(HomePage);
        OptionsButton->setObjectName(QString::fromUtf8("OptionsButton"));
        OptionsButton->setGeometry(QRect(10, 390, 271, 101));
        BolusButton = new QPushButton(HomePage);
        BolusButton->setObjectName(QString::fromUtf8("BolusButton"));
        BolusButton->setGeometry(QRect(290, 390, 271, 101));
        BatteryBar = new QProgressBar(HomePage);
        BatteryBar->setObjectName(QString::fromUtf8("BatteryBar"));
        BatteryBar->setGeometry(QRect(10, 20, 151, 30));
        BatteryBar->setValue(24);
        dateTimeEdit = new QDateTimeEdit(HomePage);
        dateTimeEdit->setObjectName(QString::fromUtf8("dateTimeEdit"));
        dateTimeEdit->setGeometry(QRect(210, 20, 141, 31));
        dateTimeEdit->setReadOnly(true);
        textEdit = new QTextEdit(HomePage);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(10, 350, 221, 31));
        textEdit->setReadOnly(true);
        inuslinUnits = new QTextEdit(HomePage);
        inuslinUnits->setObjectName(QString::fromUtf8("inuslinUnits"));
        inuslinUnits->setGeometry(QRect(260, 350, 41, 30));
        inuslinUnits->setReadOnly(true);
        currentStatus = new QPushButton(HomePage);
        currentStatus->setObjectName(QString::fromUtf8("currentStatus"));
        currentStatus->setGeometry(QRect(410, 20, 31, 31));
        stackedWidget->addWidget(HomePage);
        currentStatusPage = new QWidget();
        currentStatusPage->setObjectName(QString::fromUtf8("currentStatusPage"));
        label_55 = new QLabel(currentStatusPage);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(210, 20, 141, 31));
        QFont font;
        font.setFamily(QString::fromUtf8("DejaVu Sans"));
        font.setPointSize(14);
        label_55->setFont(font);
        backToHome_5 = new QPushButton(currentStatusPage);
        backToHome_5->setObjectName(QString::fromUtf8("backToHome_5"));
        backToHome_5->setGeometry(QRect(10, 10, 81, 41));
        buttonR = new QPushButton(currentStatusPage);
        buttonR->setObjectName(QString::fromUtf8("buttonR"));
        buttonR->setGeometry(QRect(10, 60, 501, 101));
        buttonR_2 = new QPushButton(currentStatusPage);
        buttonR_2->setObjectName(QString::fromUtf8("buttonR_2"));
        buttonR_2->setGeometry(QRect(10, 170, 501, 101));
        buttonR_3 = new QPushButton(currentStatusPage);
        buttonR_3->setObjectName(QString::fromUtf8("buttonR_3"));
        buttonR_3->setGeometry(QRect(10, 280, 501, 101));
        buttonR_4 = new QPushButton(currentStatusPage);
        buttonR_4->setObjectName(QString::fromUtf8("buttonR_4"));
        buttonR_4->setGeometry(QRect(10, 390, 501, 101));
        stackedWidget->addWidget(currentStatusPage);
        OffPage = new QWidget();
        OffPage->setObjectName(QString::fromUtf8("OffPage"));
        textBrowser = new QTextBrowser(OffPage);
        textBrowser->setObjectName(QString::fromUtf8("textBrowser"));
        textBrowser->setGeometry(QRect(10, 10, 561, 481));
        PINFrame = new QFrame(OffPage);
        PINFrame->setObjectName(QString::fromUtf8("PINFrame"));
        PINFrame->setGeometry(QRect(200, 220, 181, 91));
        PINFrame->setFrameShape(QFrame::StyledPanel);
        PINFrame->setFrameShadow(QFrame::Raised);
        label_3 = new QLabel(PINFrame);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 30, 31, 17));
        PIN = new QTextEdit(PINFrame);
        PIN->setObjectName(QString::fromUtf8("PIN"));
        PIN->setGeometry(QRect(60, 30, 101, 21));
        ErrorPIN = new QLabel(PINFrame);
        ErrorPIN->setObjectName(QString::fromUtf8("ErrorPIN"));
        ErrorPIN->setGeometry(QRect(21, 60, 141, 20));
        stackedWidget->addWidget(OffPage);
        OptionsPage = new QWidget();
        OptionsPage->setObjectName(QString::fromUtf8("OptionsPage"));
        SettingsButton = new QPushButton(OptionsPage);
        SettingsButton->setObjectName(QString::fromUtf8("SettingsButton"));
        SettingsButton->setGeometry(QRect(10, 170, 501, 101));
        backToHome_2 = new QPushButton(OptionsPage);
        backToHome_2->setObjectName(QString::fromUtf8("backToHome_2"));
        backToHome_2->setGeometry(QRect(10, 10, 81, 41));
        myPumpBTN = new QPushButton(OptionsPage);
        myPumpBTN->setObjectName(QString::fromUtf8("myPumpBTN"));
        myPumpBTN->setGeometry(QRect(10, 280, 501, 101));
        startStopBTN = new QPushButton(OptionsPage);
        startStopBTN->setObjectName(QString::fromUtf8("startStopBTN"));
        startStopBTN->setGeometry(QRect(10, 60, 501, 101));
        QFont font1;
        font1.setFamily(QString::fromUtf8("DejaVu Sans"));
        font1.setBold(true);
        font1.setWeight(75);
        startStopBTN->setFont(font1);
        startStopBTN->setStyleSheet(QString::fromUtf8("color: red;"));
        loadInsulinCartBTN = new QPushButton(OptionsPage);
        loadInsulinCartBTN->setObjectName(QString::fromUtf8("loadInsulinCartBTN"));
        loadInsulinCartBTN->setGeometry(QRect(10, 390, 501, 101));
        settingsDownButton = new QPushButton(OptionsPage);
        settingsDownButton->setObjectName(QString::fromUtf8("settingsDownButton"));
        settingsDownButton->setGeometry(QRect(520, 460, 41, 31));
        QIcon icon;
        QString iconThemeName = QString::fromUtf8("DownArrow");
        if (QIcon::hasThemeIcon(iconThemeName)) {
            icon = QIcon::fromTheme(iconThemeName);
        } else {
            icon.addFile(QString::fromUtf8("."), QSize(), QIcon::Normal, QIcon::Off);
        }
        settingsDownButton->setIcon(icon);
        label_50 = new QLabel(OptionsPage);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(260, 20, 81, 31));
        label_50->setFont(font);
        stackedWidget->addWidget(OptionsPage);
        OptionsPage2 = new QWidget();
        OptionsPage2->setObjectName(QString::fromUtf8("OptionsPage2"));
        settingsUpButton = new QPushButton(OptionsPage2);
        settingsUpButton->setObjectName(QString::fromUtf8("settingsUpButton"));
        settingsUpButton->setGeometry(QRect(520, 460, 41, 31));
        settingsUpButton->setIcon(icon);
        backToHome_4 = new QPushButton(OptionsPage2);
        backToHome_4->setObjectName(QString::fromUtf8("backToHome_4"));
        backToHome_4->setGeometry(QRect(10, 10, 81, 41));
        historyBTN = new QPushButton(OptionsPage2);
        historyBTN->setObjectName(QString::fromUtf8("historyBTN"));
        historyBTN->setGeometry(QRect(10, 60, 501, 101));
        label_51 = new QLabel(OptionsPage2);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(260, 20, 81, 31));
        label_51->setFont(font);
        stackedWidget->addWidget(OptionsPage2);
        historyPage = new QWidget();
        historyPage->setObjectName(QString::fromUtf8("historyPage"));
        backToSettingsBTN = new QPushButton(historyPage);
        backToSettingsBTN->setObjectName(QString::fromUtf8("backToSettingsBTN"));
        backToSettingsBTN->setGeometry(QRect(10, 10, 81, 41));
        pumpHistoryBTN = new QPushButton(historyPage);
        pumpHistoryBTN->setObjectName(QString::fromUtf8("pumpHistoryBTN"));
        pumpHistoryBTN->setGeometry(QRect(10, 60, 551, 101));
        cgmHistoryBTN = new QPushButton(historyPage);
        cgmHistoryBTN->setObjectName(QString::fromUtf8("cgmHistoryBTN"));
        cgmHistoryBTN->setGeometry(QRect(10, 170, 551, 101));
        label_49 = new QLabel(historyPage);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(260, 20, 71, 31));
        label_49->setFont(font);
        stackedWidget->addWidget(historyPage);
        cgmHistoryPage = new QWidget();
        cgmHistoryPage->setObjectName(QString::fromUtf8("cgmHistoryPage"));
        historyBTN_7 = new QPushButton(cgmHistoryPage);
        historyBTN_7->setObjectName(QString::fromUtf8("historyBTN_7"));
        historyBTN_7->setGeometry(QRect(10, 60, 551, 101));
        label_54 = new QLabel(cgmHistoryPage);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(230, 20, 131, 31));
        label_54->setFont(font);
        historyBTN_8 = new QPushButton(cgmHistoryPage);
        historyBTN_8->setObjectName(QString::fromUtf8("historyBTN_8"));
        historyBTN_8->setGeometry(QRect(10, 170, 551, 101));
        backToHistoryBTN_2 = new QPushButton(cgmHistoryPage);
        backToHistoryBTN_2->setObjectName(QString::fromUtf8("backToHistoryBTN_2"));
        backToHistoryBTN_2->setGeometry(QRect(10, 10, 81, 41));
        stackedWidget->addWidget(cgmHistoryPage);
        pumpHistoryPage = new QWidget();
        pumpHistoryPage->setObjectName(QString::fromUtf8("pumpHistoryPage"));
        backToHistoryBTN = new QPushButton(pumpHistoryPage);
        backToHistoryBTN->setObjectName(QString::fromUtf8("backToHistoryBTN"));
        backToHistoryBTN->setGeometry(QRect(10, 10, 81, 41));
        label_53 = new QLabel(pumpHistoryPage);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(230, 20, 131, 31));
        label_53->setFont(font);
        historyBTN_5 = new QPushButton(pumpHistoryPage);
        historyBTN_5->setObjectName(QString::fromUtf8("historyBTN_5"));
        historyBTN_5->setGeometry(QRect(10, 60, 551, 101));
        historyBTN_6 = new QPushButton(pumpHistoryPage);
        historyBTN_6->setObjectName(QString::fromUtf8("historyBTN_6"));
        historyBTN_6->setGeometry(QRect(10, 170, 551, 101));
        stackedWidget->addWidget(pumpHistoryPage);
        loadPage = new QWidget();
        loadPage->setObjectName(QString::fromUtf8("loadPage"));
        backToOptionsBTN_2 = new QPushButton(loadPage);
        backToOptionsBTN_2->setObjectName(QString::fromUtf8("backToOptionsBTN_2"));
        backToOptionsBTN_2->setGeometry(QRect(10, 10, 81, 41));
        label_34 = new QLabel(loadPage);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(270, 20, 51, 31));
        label_34->setFont(font);
        changeCartBTN = new QPushButton(loadPage);
        changeCartBTN->setObjectName(QString::fromUtf8("changeCartBTN"));
        changeCartBTN->setGeometry(QRect(10, 60, 551, 101));
        stackedWidget->addWidget(loadPage);
        stopDeliverPage = new QWidget();
        stopDeliverPage->setObjectName(QString::fromUtf8("stopDeliverPage"));
        label_35 = new QLabel(stopDeliverPage);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(50, 100, 451, 61));
        cartStopConfirmBTN = new QDialogButtonBox(stopDeliverPage);
        cartStopConfirmBTN->setObjectName(QString::fromUtf8("cartStopConfirmBTN"));
        cartStopConfirmBTN->setGeometry(QRect(180, 260, 166, 25));
        cartStopConfirmBTN->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        label_36 = new QLabel(stopDeliverPage);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(230, 180, 81, 31));
        stackedWidget->addWidget(stopDeliverPage);
        disconnectPage = new QWidget();
        disconnectPage->setObjectName(QString::fromUtf8("disconnectPage"));
        label_37 = new QLabel(disconnectPage);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(70, 100, 391, 61));
        label_38 = new QLabel(disconnectPage);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(170, 180, 181, 31));
        cartStopConfirmBTN_2 = new QDialogButtonBox(disconnectPage);
        cartStopConfirmBTN_2->setObjectName(QString::fromUtf8("cartStopConfirmBTN_2"));
        cartStopConfirmBTN_2->setGeometry(QRect(180, 260, 166, 25));
        cartStopConfirmBTN_2->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        stackedWidget->addWidget(disconnectPage);
        insulinCartSizePage = new QWidget();
        insulinCartSizePage->setObjectName(QString::fromUtf8("insulinCartSizePage"));
        label_39 = new QLabel(insulinCartSizePage);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(150, 140, 151, 61));
        insulinCartAmmountSpinBox = new QSpinBox(insulinCartSizePage);
        insulinCartAmmountSpinBox->setObjectName(QString::fromUtf8("insulinCartAmmountSpinBox"));
        insulinCartAmmountSpinBox->setGeometry(QRect(310, 150, 71, 41));
        insulinCartAmmountSpinBox->setMinimum(95);
        insulinCartAmmountSpinBox->setMaximum(300);
        continueCartBTN = new QPushButton(insulinCartSizePage);
        continueCartBTN->setObjectName(QString::fromUtf8("continueCartBTN"));
        continueCartBTN->setGeometry(QRect(240, 240, 111, 31));
        label_40 = new QLabel(insulinCartSizePage);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(390, 160, 21, 31));
        stackedWidget->addWidget(insulinCartSizePage);
        fillTubingPage = new QWidget();
        fillTubingPage->setObjectName(QString::fromUtf8("fillTubingPage"));
        label_41 = new QLabel(fillTubingPage);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(80, 100, 421, 61));
        label_42 = new QLabel(fillTubingPage);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(170, 120, 241, 61));
        label_43 = new QLabel(fillTubingPage);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(120, 230, 361, 61));
        fillTubingBTN_2 = new QPushButton(fillTubingPage);
        fillTubingBTN_2->setObjectName(QString::fromUtf8("fillTubingBTN_2"));
        fillTubingBTN_2->setGeometry(QRect(240, 300, 111, 41));
        stackedWidget->addWidget(fillTubingPage);
        setupForCannula = new QWidget();
        setupForCannula->setObjectName(QString::fromUtf8("setupForCannula"));
        label_44 = new QLabel(setupForCannula);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(20, 130, 521, 41));
        label_45 = new QLabel(setupForCannula);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(180, 170, 181, 41));
        goToCannulaFillingBTN = new QPushButton(setupForCannula);
        goToCannulaFillingBTN->setObjectName(QString::fromUtf8("goToCannulaFillingBTN"));
        goToCannulaFillingBTN->setGeometry(QRect(230, 230, 83, 25));
        stackedWidget->addWidget(setupForCannula);
        fillCannulaPage = new QWidget();
        fillCannulaPage->setObjectName(QString::fromUtf8("fillCannulaPage"));
        label_46 = new QLabel(fillCannulaPage);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(20, 130, 521, 41));
        label_47 = new QLabel(fillCannulaPage);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(190, 170, 161, 41));
        fillCannulaBTN = new QPushButton(fillCannulaPage);
        fillCannulaBTN->setObjectName(QString::fromUtf8("fillCannulaBTN"));
        fillCannulaBTN->setGeometry(QRect(230, 230, 83, 25));
        stackedWidget->addWidget(fillCannulaPage);
        resumeInsulinPage = new QWidget();
        resumeInsulinPage->setObjectName(QString::fromUtf8("resumeInsulinPage"));
        loadResumeBTN = new QDialogButtonBox(resumeInsulinPage);
        loadResumeBTN->setObjectName(QString::fromUtf8("loadResumeBTN"));
        loadResumeBTN->setGeometry(QRect(200, 230, 166, 25));
        loadResumeBTN->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        label_48 = new QLabel(resumeInsulinPage);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(110, 170, 351, 51));
        stackedWidget->addWidget(resumeInsulinPage);
        SettingsPage_1 = new QWidget();
        SettingsPage_1->setObjectName(QString::fromUtf8("SettingsPage_1"));
        DTView = new QGraphicsView(SettingsPage_1);
        DTView->setObjectName(QString::fromUtf8("DTView"));
        DTView->setGeometry(QRect(10, 10, 481, 231));
        PINView = new QGraphicsView(SettingsPage_1);
        PINView->setObjectName(QString::fromUtf8("PINView"));
        PINView->setGeometry(QRect(10, 260, 481, 231));
        DTLabel = new QLabel(SettingsPage_1);
        DTLabel->setObjectName(QString::fromUtf8("DTLabel"));
        DTLabel->setGeometry(QRect(20, 20, 81, 17));
        PINLabel = new QLabel(SettingsPage_1);
        PINLabel->setObjectName(QString::fromUtf8("PINLabel"));
        PINLabel->setGeometry(QRect(20, 270, 241, 17));
        label = new QLabel(SettingsPage_1);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(100, 310, 91, 17));
        CurrentPIN = new QTextBrowser(SettingsPage_1);
        CurrentPIN->setObjectName(QString::fromUtf8("CurrentPIN"));
        CurrentPIN->setGeometry(QRect(190, 310, 141, 21));
        DeletePINButton = new QPushButton(SettingsPage_1);
        DeletePINButton->setObjectName(QString::fromUtf8("DeletePINButton"));
        DeletePINButton->setGeometry(QRect(350, 310, 83, 25));
        NewPIN = new QTextEdit(SettingsPage_1);
        NewPIN->setObjectName(QString::fromUtf8("NewPIN"));
        NewPIN->setGeometry(QRect(190, 370, 141, 21));
        SetPINButton = new QPushButton(SettingsPage_1);
        SetPINButton->setObjectName(QString::fromUtf8("SetPINButton"));
        SetPINButton->setGeometry(QRect(220, 410, 83, 25));
        label_2 = new QLabel(SettingsPage_1);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(120, 370, 71, 17));
        ErrorNewPIN = new QLabel(SettingsPage_1);
        ErrorNewPIN->setObjectName(QString::fromUtf8("ErrorNewPIN"));
        ErrorNewPIN->setGeometry(QRect(350, 370, 81, 17));
        DownButton = new QPushButton(SettingsPage_1);
        DownButton->setObjectName(QString::fromUtf8("DownButton"));
        DownButton->setGeometry(QRect(510, 460, 41, 31));
        DownButton->setIcon(icon);
        dateTimeEditor = new QDateTimeEdit(SettingsPage_1);
        dateTimeEditor->setObjectName(QString::fromUtf8("dateTimeEditor"));
        dateTimeEditor->setGeometry(QRect(150, 90, 221, 81));
        backToHome_3 = new QPushButton(SettingsPage_1);
        backToHome_3->setObjectName(QString::fromUtf8("backToHome_3"));
        backToHome_3->setGeometry(QRect(500, 10, 51, 41));
        stackedWidget->addWidget(SettingsPage_1);
        SettingsPage_2 = new QWidget();
        SettingsPage_2->setObjectName(QString::fromUtf8("SettingsPage_2"));
        BluetoothView = new QGraphicsView(SettingsPage_2);
        BluetoothView->setObjectName(QString::fromUtf8("BluetoothView"));
        BluetoothView->setGeometry(QRect(10, 10, 481, 231));
        UpButton = new QPushButton(SettingsPage_2);
        UpButton->setObjectName(QString::fromUtf8("UpButton"));
        UpButton->setGeometry(QRect(510, 10, 41, 31));
        UpButton->setIcon(icon);
        label_5 = new QLabel(SettingsPage_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 20, 71, 17));
        BluetoothCheckBox = new QCheckBox(SettingsPage_2);
        BluetoothCheckBox->setObjectName(QString::fromUtf8("BluetoothCheckBox"));
        BluetoothCheckBox->setGeometry(QRect(30, 60, 91, 23));
        BluetoothCheckBox->setLayoutDirection(Qt::RightToLeft);
        BTMess = new QLabel(SettingsPage_2);
        BTMess->setObjectName(QString::fromUtf8("BTMess"));
        BTMess->setGeometry(QRect(140, 150, 211, 17));
        stackedWidget->addWidget(SettingsPage_2);
        leaveBolusWarningPage = new QWidget();
        leaveBolusWarningPage->setObjectName(QString::fromUtf8("leaveBolusWarningPage"));
        label_12 = new QLabel(leaveBolusWarningPage);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(80, 90, 421, 91));
        label_52 = new QLabel(leaveBolusWarningPage);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(170, 210, 241, 41));
        leaveBolusConfirm = new QDialogButtonBox(leaveBolusWarningPage);
        leaveBolusConfirm->setObjectName(QString::fromUtf8("leaveBolusConfirm"));
        leaveBolusConfirm->setGeometry(QRect(210, 250, 166, 25));
        leaveBolusConfirm->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        stackedWidget->addWidget(leaveBolusWarningPage);
        BolusPage = new QWidget();
        BolusPage->setObjectName(QString::fromUtf8("BolusPage"));
        backToHome = new QPushButton(BolusPage);
        backToHome->setObjectName(QString::fromUtf8("backToHome"));
        backToHome->setGeometry(QRect(10, 10, 81, 41));
        finalBolusUnits = new QTextEdit(BolusPage);
        finalBolusUnits->setObjectName(QString::fromUtf8("finalBolusUnits"));
        finalBolusUnits->setGeometry(QRect(120, 10, 331, 41));
        label_4 = new QLabel(BolusPage);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(270, 60, 41, 17));
        confirmBolusBTN = new QPushButton(BolusPage);
        confirmBolusBTN->setObjectName(QString::fromUtf8("confirmBolusBTN"));
        confirmBolusBTN->setGeometry(QRect(480, 10, 81, 41));
        label_6 = new QLabel(BolusPage);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(20, 140, 91, 31));
        label_7 = new QLabel(BolusPage);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(300, 140, 91, 31));
        viewCalcBTN = new QPushButton(BolusPage);
        viewCalcBTN->setObjectName(QString::fromUtf8("viewCalcBTN"));
        viewCalcBTN->setGeometry(QRect(10, 370, 551, 71));
        enterCarbsBTN = new QPushButton(BolusPage);
        enterCarbsBTN->setObjectName(QString::fromUtf8("enterCarbsBTN"));
        enterCarbsBTN->setGeometry(QRect(10, 170, 271, 141));
        addBgBTN = new QPushButton(BolusPage);
        addBgBTN->setObjectName(QString::fromUtf8("addBgBTN"));
        addBgBTN->setGeometry(QRect(290, 170, 271, 141));
        label_8 = new QLabel(BolusPage);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(130, 250, 51, 21));
        label_15 = new QLabel(BolusPage);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(400, 250, 51, 21));
        stackedWidget->addWidget(BolusPage);
        deliverCalculationPage = new QWidget();
        deliverCalculationPage->setObjectName(QString::fromUtf8("deliverCalculationPage"));
        backToBolus = new QPushButton(deliverCalculationPage);
        backToBolus->setObjectName(QString::fromUtf8("backToBolus"));
        backToBolus->setGeometry(QRect(10, 10, 81, 41));
        label_56 = new QLabel(deliverCalculationPage);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(190, 20, 201, 31));
        label_56->setFont(font);
        correctionView = new QTextEdit(deliverCalculationPage);
        correctionView->setObjectName(QString::fromUtf8("correctionView"));
        correctionView->setGeometry(QRect(310, 80, 71, 41));
        correctionView->setReadOnly(true);
        label_57 = new QLabel(deliverCalculationPage);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(140, 90, 111, 31));
        label_57->setFont(font);
        label_58 = new QLabel(deliverCalculationPage);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(170, 150, 51, 31));
        label_58->setFont(font);
        foodView = new QTextEdit(deliverCalculationPage);
        foodView->setObjectName(QString::fromUtf8("foodView"));
        foodView->setGeometry(QRect(310, 140, 71, 41));
        foodView->setReadOnly(true);
        label_59 = new QLabel(deliverCalculationPage);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(170, 210, 111, 31));
        label_59->setFont(font);
        iobView = new QTextEdit(deliverCalculationPage);
        iobView->setObjectName(QString::fromUtf8("iobView"));
        iobView->setGeometry(QRect(310, 200, 71, 41));
        iobView->setReadOnly(true);
        label_60 = new QLabel(deliverCalculationPage);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(100, 270, 201, 31));
        label_60->setFont(font);
        totalUnitsToDeliverView = new QTextEdit(deliverCalculationPage);
        totalUnitsToDeliverView->setObjectName(QString::fromUtf8("totalUnitsToDeliverView"));
        totalUnitsToDeliverView->setGeometry(QRect(310, 260, 71, 41));
        totalUnitsToDeliverView->setReadOnly(true);
        label_61 = new QLabel(deliverCalculationPage);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(140, 330, 111, 31));
        label_61->setFont(font);
        carbRatioView = new QTextEdit(deliverCalculationPage);
        carbRatioView->setObjectName(QString::fromUtf8("carbRatioView"));
        carbRatioView->setGeometry(QRect(310, 320, 71, 41));
        carbRatioView->setReadOnly(true);
        correctionFactorView = new QTextEdit(deliverCalculationPage);
        correctionFactorView->setObjectName(QString::fromUtf8("correctionFactorView"));
        correctionFactorView->setGeometry(QRect(310, 380, 71, 41));
        correctionFactorView->setReadOnly(true);
        label_141 = new QLabel(deliverCalculationPage);
        label_141->setObjectName(QString::fromUtf8("label_141"));
        label_141->setGeometry(QRect(110, 390, 171, 31));
        label_141->setFont(font);
        tagetBgView = new QTextEdit(deliverCalculationPage);
        tagetBgView->setObjectName(QString::fromUtf8("tagetBgView"));
        tagetBgView->setGeometry(QRect(310, 440, 71, 41));
        tagetBgView->setReadOnly(true);
        label_142 = new QLabel(deliverCalculationPage);
        label_142->setObjectName(QString::fromUtf8("label_142"));
        label_142->setGeometry(QRect(140, 450, 101, 31));
        label_142->setFont(font);
        label_143 = new QLabel(deliverCalculationPage);
        label_143->setObjectName(QString::fromUtf8("label_143"));
        label_143->setGeometry(QRect(390, 90, 16, 17));
        label_144 = new QLabel(deliverCalculationPage);
        label_144->setObjectName(QString::fromUtf8("label_144"));
        label_144->setGeometry(QRect(390, 210, 16, 17));
        label_145 = new QLabel(deliverCalculationPage);
        label_145->setObjectName(QString::fromUtf8("label_145"));
        label_145->setGeometry(QRect(390, 270, 16, 17));
        label_146 = new QLabel(deliverCalculationPage);
        label_146->setObjectName(QString::fromUtf8("label_146"));
        label_146->setGeometry(QRect(390, 330, 16, 17));
        label_147 = new QLabel(deliverCalculationPage);
        label_147->setObjectName(QString::fromUtf8("label_147"));
        label_147->setGeometry(QRect(390, 390, 51, 17));
        label_148 = new QLabel(deliverCalculationPage);
        label_148->setObjectName(QString::fromUtf8("label_148"));
        label_148->setGeometry(QRect(390, 450, 51, 17));
        stackedWidget->addWidget(deliverCalculationPage);
        enterCarbsPage = new QWidget();
        enterCarbsPage->setObjectName(QString::fromUtf8("enterCarbsPage"));
        textEdit_7 = new QTextEdit(enterCarbsPage);
        textEdit_7->setObjectName(QString::fromUtf8("textEdit_7"));
        textEdit_7->setGeometry(QRect(120, 10, 331, 41));
        textEdit_7->setReadOnly(true);
        BTN0 = new QPushButton(enterCarbsPage);
        BTN0->setObjectName(QString::fromUtf8("BTN0"));
        BTN0->setGeometry(QRect(10, 10, 81, 41));
        addCarbsBTN = new QPushButton(enterCarbsPage);
        addCarbsBTN->setObjectName(QString::fromUtf8("addCarbsBTN"));
        addCarbsBTN->setGeometry(QRect(480, 10, 81, 41));
        label_9 = new QLabel(enterCarbsPage);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(210, 190, 41, 17));
        carbGramsSpinBox = new QDoubleSpinBox(enterCarbsPage);
        carbGramsSpinBox->setObjectName(QString::fromUtf8("carbGramsSpinBox"));
        carbGramsSpinBox->setGeometry(QRect(260, 180, 101, 41));
        stackedWidget->addWidget(enterCarbsPage);
        enterBgPage = new QWidget();
        enterBgPage->setObjectName(QString::fromUtf8("enterBgPage"));
        bgSpinBox = new QDoubleSpinBox(enterBgPage);
        bgSpinBox->setObjectName(QString::fromUtf8("bgSpinBox"));
        bgSpinBox->setGeometry(QRect(260, 180, 101, 41));
        textEdit_8 = new QTextEdit(enterBgPage);
        textEdit_8->setObjectName(QString::fromUtf8("textEdit_8"));
        textEdit_8->setGeometry(QRect(120, 10, 331, 41));
        textEdit_8->setReadOnly(true);
        label_14 = new QLabel(enterBgPage);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(200, 190, 51, 16));
        addBgBTN_2 = new QPushButton(enterBgPage);
        addBgBTN_2->setObjectName(QString::fromUtf8("addBgBTN_2"));
        addBgBTN_2->setGeometry(QRect(480, 10, 81, 41));
        backToBolusBTN = new QPushButton(enterBgPage);
        backToBolusBTN->setObjectName(QString::fromUtf8("backToBolusBTN"));
        backToBolusBTN->setGeometry(QRect(10, 10, 81, 41));
        stackedWidget->addWidget(enterBgPage);
        confirmBolusPage = new QWidget();
        confirmBolusPage->setObjectName(QString::fromUtf8("confirmBolusPage"));
        label_16 = new QLabel(confirmBolusPage);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(210, 20, 171, 31));
        label_16->setFont(font);
        label_17 = new QLabel(confirmBolusPage);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(170, 90, 62, 17));
        label_18 = new QLabel(confirmBolusPage);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(170, 160, 62, 17));
        label_19 = new QLabel(confirmBolusPage);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(170, 230, 111, 17));
        conCarb = new QTextEdit(confirmBolusPage);
        conCarb->setObjectName(QString::fromUtf8("conCarb"));
        conCarb->setGeometry(QRect(300, 80, 61, 31));
        conCarb->setReadOnly(true);
        conBG = new QTextEdit(confirmBolusPage);
        conBG->setObjectName(QString::fromUtf8("conBG"));
        conBG->setGeometry(QRect(300, 150, 61, 31));
        conBG->setReadOnly(true);
        conUnits = new QTextEdit(confirmBolusPage);
        conUnits->setObjectName(QString::fromUtf8("conUnits"));
        conUnits->setGeometry(QRect(300, 220, 61, 31));
        conUnits->setReadOnly(true);
        label_20 = new QLabel(confirmBolusPage);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(370, 90, 62, 17));
        label_21 = new QLabel(confirmBolusPage);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(370, 160, 62, 17));
        label_22 = new QLabel(confirmBolusPage);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(370, 230, 62, 17));
        buttonBox = new QDialogButtonBox(confirmBolusPage);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setGeometry(QRect(210, 290, 166, 25));
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        stackedWidget->addWidget(confirmBolusPage);
        deliverBolusPage = new QWidget();
        deliverBolusPage->setObjectName(QString::fromUtf8("deliverBolusPage"));
        label_23 = new QLabel(deliverBolusPage);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(210, 20, 181, 31));
        label_23->setFont(font);
        label_24 = new QLabel(deliverBolusPage);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(200, 100, 71, 17));
        label_25 = new QLabel(deliverBolusPage);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(210, 220, 71, 17));
        correctionAmount = new QTextEdit(deliverBolusPage);
        correctionAmount->setObjectName(QString::fromUtf8("correctionAmount"));
        correctionAmount->setGeometry(QRect(300, 90, 71, 31));
        correctionAmount->setReadOnly(true);
        foodAmount = new QTextEdit(deliverBolusPage);
        foodAmount->setObjectName(QString::fromUtf8("foodAmount"));
        foodAmount->setGeometry(QRect(300, 210, 71, 31));
        foodAmount->setReadOnly(true);
        label_26 = new QLabel(deliverBolusPage);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(380, 100, 71, 17));
        label_27 = new QLabel(deliverBolusPage);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(380, 220, 71, 17));
        confirmBolBTN = new QDialogButtonBox(deliverBolusPage);
        confirmBolBTN->setObjectName(QString::fromUtf8("confirmBolBTN"));
        confirmBolBTN->setGeometry(QRect(210, 290, 166, 25));
        confirmBolBTN->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        ExtensionCheckBox = new QCheckBox(deliverBolusPage);
        ExtensionCheckBox->setObjectName(QString::fromUtf8("ExtensionCheckBox"));
        ExtensionCheckBox->setGeometry(QRect(200, 160, 90, 23));
        editExtensionBTN = new QPushButton(deliverBolusPage);
        editExtensionBTN->setObjectName(QString::fromUtf8("editExtensionBTN"));
        editExtensionBTN->setGeometry(QRect(290, 160, 101, 25));
        stackedWidget->addWidget(deliverBolusPage);
        extendedPage = new QWidget();
        extendedPage->setObjectName(QString::fromUtf8("extendedPage"));
        textEdit_9 = new QTextEdit(extendedPage);
        textEdit_9->setObjectName(QString::fromUtf8("textEdit_9"));
        textEdit_9->setGeometry(QRect(120, 10, 331, 41));
        textEdit_9->setReadOnly(true);
        setDeliveryTimeBTN = new QPushButton(extendedPage);
        setDeliveryTimeBTN->setObjectName(QString::fromUtf8("setDeliveryTimeBTN"));
        setDeliveryTimeBTN->setGeometry(QRect(480, 10, 81, 41));
        backToDeliverBTN = new QPushButton(extendedPage);
        backToDeliverBTN->setObjectName(QString::fromUtf8("backToDeliverBTN"));
        backToDeliverBTN->setGeometry(QRect(10, 10, 81, 41));
        label_28 = new QLabel(extendedPage);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(270, 60, 62, 17));
        deliverNowBTN = new QPushButton(extendedPage);
        deliverNowBTN->setObjectName(QString::fromUtf8("deliverNowBTN"));
        deliverNowBTN->setGeometry(QRect(20, 130, 251, 131));
        QFont font2;
        font2.setFamily(QString::fromUtf8("DejaVu Sans"));
        font2.setPointSize(18);
        deliverNowBTN->setFont(font2);
        label_29 = new QLabel(extendedPage);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(20, 100, 101, 31));
        label_30 = new QLabel(extendedPage);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(310, 100, 111, 31));
        label_31 = new QLabel(extendedPage);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(20, 300, 101, 31));
        extendedDurationBTN = new QPushButton(extendedPage);
        extendedDurationBTN->setObjectName(QString::fromUtf8("extendedDurationBTN"));
        extendedDurationBTN->setGeometry(QRect(20, 330, 251, 71));
        viewExtendedUnitsBTN = new QPushButton(extendedPage);
        viewExtendedUnitsBTN->setObjectName(QString::fromUtf8("viewExtendedUnitsBTN"));
        viewExtendedUnitsBTN->setGeometry(QRect(310, 330, 251, 71));
        deliverLaterLabel2 = new QTextEdit(extendedPage);
        deliverLaterLabel2->setObjectName(QString::fromUtf8("deliverLaterLabel2"));
        deliverLaterLabel2->setGeometry(QRect(310, 130, 251, 131));
        deliverLaterLabel2->setReadOnly(true);
        deliverLaterLabel = new QLabel(extendedPage);
        deliverLaterLabel->setObjectName(QString::fromUtf8("deliverLaterLabel"));
        deliverLaterLabel->setGeometry(QRect(410, 170, 71, 41));
        QFont font3;
        font3.setFamily(QString::fromUtf8("DejaVu Sans"));
        font3.setPointSize(18);
        font3.setBold(false);
        font3.setWeight(50);
        deliverLaterLabel->setFont(font3);
        deliverLaterLabel->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(extendedPage);
        deliverNowPercentagePage = new QWidget();
        deliverNowPercentagePage->setObjectName(QString::fromUtf8("deliverNowPercentagePage"));
        backToExtendedPageBTN = new QPushButton(deliverNowPercentagePage);
        backToExtendedPageBTN->setObjectName(QString::fromUtf8("backToExtendedPageBTN"));
        backToExtendedPageBTN->setGeometry(QRect(10, 10, 81, 41));
        setDeliverBTN = new QPushButton(deliverNowPercentagePage);
        setDeliverBTN->setObjectName(QString::fromUtf8("setDeliverBTN"));
        setDeliverBTN->setGeometry(QRect(480, 10, 81, 41));
        textEdit_11 = new QTextEdit(deliverNowPercentagePage);
        textEdit_11->setObjectName(QString::fromUtf8("textEdit_11"));
        textEdit_11->setGeometry(QRect(120, 10, 331, 41));
        textEdit_11->setReadOnly(true);
        deliverNowSpinbox = new QSpinBox(deliverNowPercentagePage);
        deliverNowSpinbox->setObjectName(QString::fromUtf8("deliverNowSpinbox"));
        deliverNowSpinbox->setGeometry(QRect(240, 180, 101, 41));
        deliverNowSpinbox->setValue(50);
        stackedWidget->addWidget(deliverNowPercentagePage);
        timeDurationPage = new QWidget();
        timeDurationPage->setObjectName(QString::fromUtf8("timeDurationPage"));
        setTimeDurBTN = new QPushButton(timeDurationPage);
        setTimeDurBTN->setObjectName(QString::fromUtf8("setTimeDurBTN"));
        setTimeDurBTN->setGeometry(QRect(480, 10, 81, 41));
        setHourSpinbox = new QSpinBox(timeDurationPage);
        setHourSpinbox->setObjectName(QString::fromUtf8("setHourSpinbox"));
        setHourSpinbox->setGeometry(QRect(200, 180, 61, 41));
        setHourSpinbox->setMaximum(23);
        setHourSpinbox->setValue(2);
        textEdit_12 = new QTextEdit(timeDurationPage);
        textEdit_12->setObjectName(QString::fromUtf8("textEdit_12"));
        textEdit_12->setGeometry(QRect(120, 10, 331, 41));
        textEdit_12->setReadOnly(true);
        backToExtendedPageBTN_2 = new QPushButton(timeDurationPage);
        backToExtendedPageBTN_2->setObjectName(QString::fromUtf8("backToExtendedPageBTN_2"));
        backToExtendedPageBTN_2->setGeometry(QRect(10, 10, 81, 41));
        setMinSpinbox = new QSpinBox(timeDurationPage);
        setMinSpinbox->setObjectName(QString::fromUtf8("setMinSpinbox"));
        setMinSpinbox->setGeometry(QRect(310, 180, 61, 41));
        setMinSpinbox->setMaximum(59);
        label_32 = new QLabel(timeDurationPage);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(200, 160, 62, 17));
        label_33 = new QLabel(timeDurationPage);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(310, 160, 62, 17));
        stackedWidget->addWidget(timeDurationPage);
        deliverConfirmPage = new QWidget();
        deliverConfirmPage->setObjectName(QString::fromUtf8("deliverConfirmPage"));
        deliverNowLabel = new QTextEdit(deliverConfirmPage);
        deliverNowLabel->setObjectName(QString::fromUtf8("deliverNowLabel"));
        deliverNowLabel->setGeometry(QRect(280, 80, 61, 31));
        deliverNowLabel->setReadOnly(true);
        durationButtonBox = new QDialogButtonBox(deliverConfirmPage);
        durationButtonBox->setObjectName(QString::fromUtf8("durationButtonBox"));
        durationButtonBox->setGeometry(QRect(190, 290, 166, 25));
        durationButtonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        label_67 = new QLabel(deliverConfirmPage);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(190, 20, 171, 31));
        label_67->setFont(font);
        deliverLaterLabel_3 = new QTextEdit(deliverConfirmPage);
        deliverLaterLabel_3->setObjectName(QString::fromUtf8("deliverLaterLabel_3"));
        deliverLaterLabel_3->setGeometry(QRect(280, 150, 61, 31));
        deliverLaterLabel_3->setReadOnly(true);
        durationLabel = new QTextEdit(deliverConfirmPage);
        durationLabel->setObjectName(QString::fromUtf8("durationLabel"));
        durationLabel->setGeometry(QRect(220, 220, 181, 31));
        durationLabel->setReadOnly(true);
        label_68 = new QLabel(deliverConfirmPage);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(190, 90, 81, 17));
        label_69 = new QLabel(deliverConfirmPage);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(190, 160, 91, 17));
        label_70 = new QLabel(deliverConfirmPage);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(130, 230, 61, 17));
        stackedWidget->addWidget(deliverConfirmPage);
        finalBolusConfirmPage = new QWidget();
        finalBolusConfirmPage->setObjectName(QString::fromUtf8("finalBolusConfirmPage"));
        label_71 = new QLabel(finalBolusConfirmPage);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(170, 30, 201, 31));
        label_71->setFont(font);
        label_72 = new QLabel(finalBolusConfirmPage);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(120, 100, 121, 17));
        label_73 = new QLabel(finalBolusConfirmPage);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(190, 160, 41, 17));
        label_74 = new QLabel(finalBolusConfirmPage);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(170, 220, 71, 17));
        bolusNowAndCorrectionLabel = new QTextEdit(finalBolusConfirmPage);
        bolusNowAndCorrectionLabel->setObjectName(QString::fromUtf8("bolusNowAndCorrectionLabel"));
        bolusNowAndCorrectionLabel->setGeometry(QRect(260, 90, 101, 31));
        bolusNowAndCorrectionLabel->setReadOnly(true);
        bolusLaterLabel = new QTextEdit(finalBolusConfirmPage);
        bolusLaterLabel->setObjectName(QString::fromUtf8("bolusLaterLabel"));
        bolusLaterLabel->setGeometry(QRect(260, 150, 101, 31));
        bolusLaterLabel->setReadOnly(true);
        finalTimeDurationLabel = new QTextEdit(finalBolusConfirmPage);
        finalTimeDurationLabel->setObjectName(QString::fromUtf8("finalTimeDurationLabel"));
        finalTimeDurationLabel->setGeometry(QRect(260, 210, 171, 31));
        finalTimeDurationLabel->setReadOnly(true);
        finalConfirmBolusButtonBox = new QDialogButtonBox(finalBolusConfirmPage);
        finalConfirmBolusButtonBox->setObjectName(QString::fromUtf8("finalConfirmBolusButtonBox"));
        finalConfirmBolusButtonBox->setGeometry(QRect(190, 280, 166, 25));
        finalConfirmBolusButtonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        stackedWidget->addWidget(finalBolusConfirmPage);
        intiatedExtendedPage = new QWidget();
        intiatedExtendedPage->setObjectName(QString::fromUtf8("intiatedExtendedPage"));
        label_75 = new QLabel(intiatedExtendedPage);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(210, 90, 161, 31));
        label_75->setFont(font);
        finalBolusUnitsLabel = new QLabel(intiatedExtendedPage);
        finalBolusUnitsLabel->setObjectName(QString::fromUtf8("finalBolusUnitsLabel"));
        finalBolusUnitsLabel->setGeometry(QRect(170, 180, 251, 41));
        finalBolusUnitsLabel->setFont(font);
        stackedWidget->addWidget(intiatedExtendedPage);
        initialdedPage = new QWidget();
        initialdedPage->setObjectName(QString::fromUtf8("initialdedPage"));
        label_149 = new QLabel(initialdedPage);
        label_149->setObjectName(QString::fromUtf8("label_149"));
        label_149->setGeometry(QRect(210, 90, 161, 31));
        label_149->setFont(font);
        finalBolusUnitsLabel_3 = new QLabel(initialdedPage);
        finalBolusUnitsLabel_3->setObjectName(QString::fromUtf8("finalBolusUnitsLabel_3"));
        finalBolusUnitsLabel_3->setGeometry(QRect(270, 180, 51, 41));
        finalBolusUnitsLabel_3->setFont(font);
        stackedWidget->addWidget(initialdedPage);
        lowChargeWarningPage = new QWidget();
        lowChargeWarningPage->setObjectName(QString::fromUtf8("lowChargeWarningPage"));
        label_10 = new QLabel(lowChargeWarningPage);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(180, 150, 211, 41));
        label_11 = new QLabel(lowChargeWarningPage);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(170, 240, 231, 41));
        stackedWidget->addWidget(lowChargeWarningPage);
        myPumpPage = new QWidget();
        myPumpPage->setObjectName(QString::fromUtf8("myPumpPage"));
        personalProfilesBTN = new QPushButton(myPumpPage);
        personalProfilesBTN->setObjectName(QString::fromUtf8("personalProfilesBTN"));
        personalProfilesBTN->setGeometry(QRect(10, 60, 541, 81));
        backToOptionsBTN = new QPushButton(myPumpPage);
        backToOptionsBTN->setObjectName(QString::fromUtf8("backToOptionsBTN"));
        backToOptionsBTN->setGeometry(QRect(10, 10, 81, 41));
        pumpInfoBTN = new QPushButton(myPumpPage);
        pumpInfoBTN->setObjectName(QString::fromUtf8("pumpInfoBTN"));
        pumpInfoBTN->setGeometry(QRect(10, 150, 541, 81));
        stackedWidget->addWidget(myPumpPage);
        personalProfilesPage = new QWidget();
        personalProfilesPage->setObjectName(QString::fromUtf8("personalProfilesPage"));
        createProfilePageBTN = new QPushButton(personalProfilesPage);
        createProfilePageBTN->setObjectName(QString::fromUtf8("createProfilePageBTN"));
        createProfilePageBTN->setGeometry(QRect(380, 10, 181, 41));
        backToMyPumpBTN = new QPushButton(personalProfilesPage);
        backToMyPumpBTN->setObjectName(QString::fromUtf8("backToMyPumpBTN"));
        backToMyPumpBTN->setGeometry(QRect(10, 10, 81, 41));
        profileTable = new QTableWidget(personalProfilesPage);
        if (profileTable->columnCount() < 3)
            profileTable->setColumnCount(3);
        QFont font4;
        font4.setFamily(QString::fromUtf8("DejaVu Sans"));
        font4.setPointSize(12);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setTextAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        __qtablewidgetitem->setFont(font4);
        profileTable->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QFont font5;
        font5.setFamily(QString::fromUtf8("DejaVu Sans"));
        font5.setPointSize(12);
        font5.setItalic(false);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        __qtablewidgetitem1->setTextAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        __qtablewidgetitem1->setFont(font5);
        profileTable->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QFont font6;
        font6.setFamily(QString::fromUtf8("DejaVu Sans"));
        font6.setPointSize(12);
        font6.setItalic(true);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        __qtablewidgetitem2->setTextAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        __qtablewidgetitem2->setFont(font6);
        profileTable->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        profileTable->setObjectName(QString::fromUtf8("profileTable"));
        profileTable->setGeometry(QRect(100, 140, 401, 211));
        stackedWidget->addWidget(personalProfilesPage);
        profileNameCreatePage = new QWidget();
        profileNameCreatePage->setObjectName(QString::fromUtf8("profileNameCreatePage"));
        profileNameLineEdit = new QLineEdit(profileNameCreatePage);
        profileNameLineEdit->setObjectName(QString::fromUtf8("profileNameLineEdit"));
        profileNameLineEdit->setGeometry(QRect(210, 190, 151, 41));
        label_13 = new QLabel(profileNameCreatePage);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(220, 170, 130, 21));
        createProfileBTN = new QPushButton(profileNameCreatePage);
        createProfileBTN->setObjectName(QString::fromUtf8("createProfileBTN"));
        createProfileBTN->setGeometry(QRect(240, 280, 83, 25));
        nameErrorLabel = new QLabel(profileNameCreatePage);
        nameErrorLabel->setObjectName(QString::fromUtf8("nameErrorLabel"));
        nameErrorLabel->setGeometry(QRect(70, 70, 451, 71));
        QFont font7;
        font7.setFamily(QString::fromUtf8("DejaVu Sans"));
        font7.setPointSize(26);
        nameErrorLabel->setFont(font7);
        nameErrorLabel->setStyleSheet(QString::fromUtf8("color: red;"));
        backToPersonalProfilesPageBTN = new QPushButton(profileNameCreatePage);
        backToPersonalProfilesPageBTN->setObjectName(QString::fromUtf8("backToPersonalProfilesPageBTN"));
        backToPersonalProfilesPageBTN->setGeometry(QRect(10, 10, 81, 41));
        stackedWidget->addWidget(profileNameCreatePage);
        OnButton = new QPushButton(centralwidget);
        OnButton->setObjectName(QString::fromUtf8("OnButton"));
        OnButton->setGeometry(QRect(710, 70, 83, 25));
        OffButton = new QPushButton(centralwidget);
        OffButton->setObjectName(QString::fromUtf8("OffButton"));
        OffButton->setGeometry(QRect(710, 120, 83, 25));
        ChargeButton = new QPushButton(centralwidget);
        ChargeButton->setObjectName(QString::fromUtf8("ChargeButton"));
        ChargeButton->setGeometry(QRect(710, 350, 83, 25));
        UnplugButton = new QPushButton(centralwidget);
        UnplugButton->setObjectName(QString::fromUtf8("UnplugButton"));
        UnplugButton->setGeometry(QRect(710, 390, 83, 25));
        TandemLogo = new QPushButton(centralwidget);
        TandemLogo->setObjectName(QString::fromUtf8("TandemLogo"));
        TandemLogo->setGeometry(QRect(590, 10, 111, 481));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 803, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(16);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
#if QT_CONFIG(statustip)
        BolusBar->setStatusTip(QCoreApplication::translate("MainWindow", "%p%", nullptr));
#endif // QT_CONFIG(statustip)
        BolusBar->setFormat(QString());
        OptionsButton->setText(QCoreApplication::translate("MainWindow", "OPTIONS", nullptr));
        BolusButton->setText(QCoreApplication::translate("MainWindow", "BOLUS", nullptr));
        textEdit->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">INSULIN ON BOARD (IOB)</span></p></body></html>", nullptr));
        inuslinUnits->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        currentStatus->setText(QCoreApplication::translate("MainWindow", "B", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindow", "Current Status", nullptr));
        backToHome_5->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        buttonR->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        buttonR_2->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        buttonR_3->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        buttonR_4->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        textBrowser->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px"
                        ";\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">OFF</p></body></html>", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "PIN:", nullptr));
        ErrorPIN->setText(QString());
        SettingsButton->setText(QCoreApplication::translate("MainWindow", "Settings", nullptr));
        backToHome_2->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        myPumpBTN->setText(QCoreApplication::translate("MainWindow", "My Pump", nullptr));
        startStopBTN->setText(QCoreApplication::translate("MainWindow", "START INSULIN", nullptr));
        loadInsulinCartBTN->setText(QCoreApplication::translate("MainWindow", "Load Insulin Cartirage", nullptr));
        settingsDownButton->setText(QCoreApplication::translate("MainWindow", "\\/", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "Options", nullptr));
        settingsUpButton->setText(QCoreApplication::translate("MainWindow", "/\\", nullptr));
        backToHome_4->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        historyBTN->setText(QCoreApplication::translate("MainWindow", "History", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "Options", nullptr));
        backToSettingsBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        pumpHistoryBTN->setText(QCoreApplication::translate("MainWindow", "Pump History", nullptr));
        cgmHistoryBTN->setText(QCoreApplication::translate("MainWindow", "CGM History", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "History", nullptr));
        historyBTN_7->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", " CGM History", nullptr));
        historyBTN_8->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        backToHistoryBTN_2->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        backToHistoryBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "Pump History", nullptr));
        historyBTN_5->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        historyBTN_6->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        backToOptionsBTN_2->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Load", nullptr));
        changeCartBTN->setText(QCoreApplication::translate("MainWindow", "Change Cartridge", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "In order to change a cartridge, all insulin deliveries will be stopped.", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Continue?", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Make sure the infusion set is disconnected from your body.", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Are you ready to continue?", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Insulin Cartridge Size:", nullptr));
        continueCartBTN->setText(QCoreApplication::translate("MainWindow", "Continue", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "u", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Make sure the set is disconnected from your body and securely", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "connect the tubing to your cartridge.", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "On the next screen, you will fill your tubing with insulin.", nullptr));
        fillTubingBTN_2->setText(QCoreApplication::translate("MainWindow", "Fill Tubing", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "If you see drops at the end of the tubing, press Done. If not, wait till the tube is", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "filled before pressing Done.", nullptr));
        goToCannulaFillingBTN->setText(QCoreApplication::translate("MainWindow", "DONE", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "Insert a new set and connect to the filled tubing. When pressing next, it will fill", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "the cannula with insulin.", nullptr));
        fillCannulaBTN->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindow", "All done! Would you like to resume the insuling now?", nullptr));
        DTLabel->setText(QCoreApplication::translate("MainWindow", "Date / Time", nullptr));
        PINLabel->setText(QCoreApplication::translate("MainWindow", "PIN (Personal Identification Number)", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Current PIN:", nullptr));
        DeletePINButton->setText(QCoreApplication::translate("MainWindow", "Delete PIN", nullptr));
        SetPINButton->setText(QCoreApplication::translate("MainWindow", "Set PIN", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "New PIN:", nullptr));
        ErrorNewPIN->setText(QString());
        DownButton->setText(QCoreApplication::translate("MainWindow", "\\/", nullptr));
        backToHome_3->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        UpButton->setText(QCoreApplication::translate("MainWindow", "/\\", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Bluetooth", nullptr));
        BluetoothCheckBox->setText(QCoreApplication::translate("MainWindow", "Bluetooth", nullptr));
        BTMess->setText(QString());
        label_12->setText(QCoreApplication::translate("MainWindow", "You are in the middle of a process that impacts insulin delivery.", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "Would you still like to return home?", nullptr));
        backToHome->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        finalBolusUnits->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">0</span></p></body></html>", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "units", nullptr));
        confirmBolusBTN->setText(QCoreApplication::translate("MainWindow", "\342\234\223", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "CARBS", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "GLUCOSE", nullptr));
        viewCalcBTN->setText(QCoreApplication::translate("MainWindow", "View Calculation", nullptr));
        enterCarbsBTN->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        addBgBTN->setText(QCoreApplication::translate("MainWindow", "Add BG", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "grams", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "mmol/L", nullptr));
        backToBolus->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindow", "Delivery Calculations", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindow", "Correction", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "Food", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindow", "IOB", nullptr));
        label_60->setText(QCoreApplication::translate("MainWindow", "Total Units To Deliver", nullptr));
        label_61->setText(QCoreApplication::translate("MainWindow", "Carb Ratio", nullptr));
        label_141->setText(QCoreApplication::translate("MainWindow", "Correction Factor", nullptr));
        label_142->setText(QCoreApplication::translate("MainWindow", "Target BG", nullptr));
        label_143->setText(QCoreApplication::translate("MainWindow", "u", nullptr));
        label_144->setText(QCoreApplication::translate("MainWindow", "u", nullptr));
        label_145->setText(QCoreApplication::translate("MainWindow", "u", nullptr));
        label_146->setText(QCoreApplication::translate("MainWindow", "g", nullptr));
        label_147->setText(QCoreApplication::translate("MainWindow", "mmol/L", nullptr));
        label_148->setText(QCoreApplication::translate("MainWindow", "mmol/L", nullptr));
        textEdit_7->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Enter Carbs</span></p></body></html>", nullptr));
        BTN0->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        addCarbsBTN->setText(QCoreApplication::translate("MainWindow", "\342\234\223", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "grams", nullptr));
        textEdit_8->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Enter Blood Glucose</span></p></body></html>", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "mmol/L", nullptr));
        addBgBTN_2->setText(QCoreApplication::translate("MainWindow", "\342\234\223", nullptr));
        backToBolusBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Confirm Request?", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Carbs", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "BG", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Units To Deliver", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "g", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "mmol/L", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "u", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Deliver The Bolus?", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Correction", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Food", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "u", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "u", nullptr));
        ExtensionCheckBox->setText(QCoreApplication::translate("MainWindow", "Extension", nullptr));
        editExtensionBTN->setText(QCoreApplication::translate("MainWindow", "Edit Extension", nullptr));
        textEdit_9->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">0</span></p></body></html>", nullptr));
        setDeliveryTimeBTN->setText(QCoreApplication::translate("MainWindow", "\342\234\223", nullptr));
        backToDeliverBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "units", nullptr));
        deliverNowBTN->setText(QCoreApplication::translate("MainWindow", "50%", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "DELIVER NOW", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "DELIVER LATER", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "DURATION", nullptr));
        extendedDurationBTN->setText(QCoreApplication::translate("MainWindow", "2 hrs", nullptr));
        viewExtendedUnitsBTN->setText(QCoreApplication::translate("MainWindow", "View Units", nullptr));
        deliverLaterLabel2->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        deliverLaterLabel->setText(QCoreApplication::translate("MainWindow", "50%", nullptr));
        backToExtendedPageBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        setDeliverBTN->setText(QCoreApplication::translate("MainWindow", "\342\234\223", nullptr));
        textEdit_11->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Set Deliver Percentage</span></p></body></html>", nullptr));
        setTimeDurBTN->setText(QCoreApplication::translate("MainWindow", "\342\234\223", nullptr));
        textEdit_12->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Set Time Duration</span></p></body></html>", nullptr));
        backToExtendedPageBTN_2->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "hours", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "minutes", nullptr));
        label_67->setText(QCoreApplication::translate("MainWindow", "Confirm Request?", nullptr));
        label_68->setText(QCoreApplication::translate("MainWindow", "Deliver Now", nullptr));
        label_69->setText(QCoreApplication::translate("MainWindow", "Deliver Later", nullptr));
        label_70->setText(QCoreApplication::translate("MainWindow", "Duration", nullptr));
        label_71->setText(QCoreApplication::translate("MainWindow", "Deliver 0.0 u Bolus?", nullptr));
        label_72->setText(QCoreApplication::translate("MainWindow", "Now + Correction", nullptr));
        label_73->setText(QCoreApplication::translate("MainWindow", "Later", nullptr));
        label_74->setText(QCoreApplication::translate("MainWindow", "Duration", nullptr));
        label_75->setText(QCoreApplication::translate("MainWindow", "BOLUS INITIATED", nullptr));
        finalBolusUnitsLabel->setText(QCoreApplication::translate("MainWindow", "0.0 u Now + 0.0 u Later", nullptr));
        label_149->setText(QCoreApplication::translate("MainWindow", "BOLUS INITIATED", nullptr));
        finalBolusUnitsLabel_3->setText(QCoreApplication::translate("MainWindow", "0.0 u", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "WARNING, BATTERY LEVEL LOW", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "PLEASE START CHARGING DEVICE", nullptr));
        personalProfilesBTN->setText(QCoreApplication::translate("MainWindow", "Personal Profiles", nullptr));
        backToOptionsBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        pumpInfoBTN->setText(QCoreApplication::translate("MainWindow", "Pump Info", nullptr));
        createProfilePageBTN->setText(QCoreApplication::translate("MainWindow", "Create New Profile", nullptr));
        backToMyPumpBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        QTableWidgetItem *___qtablewidgetitem = profileTable->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindow", "Profile Name", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = profileTable->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindow", "Select Profile", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = profileTable->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindow", "Edit", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Enter  Profile  Name", nullptr));
        createProfileBTN->setText(QCoreApplication::translate("MainWindow", "Create", nullptr));
        nameErrorLabel->setText(QString());
        backToPersonalProfilesPageBTN->setText(QCoreApplication::translate("MainWindow", "<--", nullptr));
        OnButton->setText(QCoreApplication::translate("MainWindow", "ON", nullptr));
        OffButton->setText(QCoreApplication::translate("MainWindow", "OFF", nullptr));
        ChargeButton->setText(QCoreApplication::translate("MainWindow", "Charge", nullptr));
        UnplugButton->setText(QCoreApplication::translate("MainWindow", "Unplug", nullptr));
        TandemLogo->setText(QCoreApplication::translate("MainWindow", "Tandem", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
